sudo: required
services:
  - docker

before_install:
  - docker build -t mack031892/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mack031892/react-test npm run test --coverage

after_success:
  - docker build -t mack031892/complex-client ./client
  - docker build -t mack031892/complex-nginx ./nginx
  - docker build -t mack031892/complex-server ./server
  - docker build -t mack031892/complex-worker ./worker
  # LOGIN TO DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # TAKE THOSE IMAGES TO PUSH TO DOCKER HUB
  - docker push mack031892/complex-client
  - docker push mack031892/complex-nginx
  - docker push mack031892/complex-server
  - docker push mack031892/complex-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: complex-proejct
  env: Complexproejct-env
  bucket_name: elasticbeanstalk-ap-southeast-1-249436949423
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
