version: '3'
services:
  nginx:
    image: mack031892/complex-nginx
    restart: always
    ports:
      - '80:80'
    mem_limit: 128m
    links:
      - client
      - api
  api:
    image: mack031892/complex-server
    mem_limit: 128m
    environment:
      REDIS_HOST: complex-project.dun2yu.ng.0001.apse1.cache.amazonaws.com
      REDIS_PORT: 6379
      PG_HOST: complex-project-rds.c7jpwjt3ogux.ap-southeast-1.rds.amazonaws.com
      PG_USER: postgres
      PG_DATABASE: postgres
      PG_PASSWORD: postgres_password
      PG_PORT: 5432
  client:
    image: mack031892/complex-client
    mem_limit: 128m
  worker:
    image: mack031892/complex-worker
    mem_limit: 128m
