version: '3'
services:
  api:
    image: mack031892/complex-server
    mem_limit: 128m
  client:
    image: mack031892/complex-client
    mem_limit: 128m
  worker:
    image: mack031892/complex-worker
    mem_limit: 128m
  nginx:
    image: mack031892/complex-nginx
    restart: always
    ports:
      - '5000:80'
    mem_limit: 128m
    links:
      - client
      - api
