version: '3'
services:
  nginx:
    image: mack031892/complex-nginx
    restart: always
    ports:
      - '80:80'
    mem_limit: 128m
    links:
      - api
      - client
  api:
    image: mack031892/complex-server
    mem_limit: 128m
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - PG_HOST=postgres
    #   - PG_USER=postgres
    #   - PG_DATABASE=postgres
    #   - PG_PASSWORD=postgres
    #   - PG_PORT=5432
  client:
    image: mack031892/complex-client
    mem_limit: 128m
  worker:
    image: mack031892/complex-worker
    mem_limit: 128m
